{"name": "Негативная проверка авторизации юзера с неправильным майлом или паролем", "status": "passed", "description": "Запрос должен вернуть ошибку и правильный код ответа", "attachments": [{"name": "stdout", "source": "389350ee-ecbf-452b-90b3-216d10497fce-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "wrong_value", "value": "'password'"}], "start": 1723366550851, "stop": 1723366551365, "uuid": "7630ade3-2209-43cf-bd10-c5cec6e80817", "historyId": "bd8e77bfcc9044596f24cf35f4361a43", "testCaseId": "4d86218e2daabd1383135081cc8a8b93", "fullName": "tests.test_authorization_courier.test_authorization_with_wrong_password_or_email.TestAutorizationUser#test_authorization_user_with_wrong_password_or_email_error", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('reg')"}, {"name": "parentSuite", "value": "tests.test_authorization_courier"}, {"name": "suite", "value": "test_authorization_with_wrong_password_or_email"}, {"name": "subSuite", "value": "TestAutorizationUser"}, {"name": "host", "value": "DESKTOP-IKUPUFD"}, {"name": "thread", "value": "16804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorization_courier.test_authorization_with_wrong_password_or_email"}]}